// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://localhost:7080' | (string & {});
};

export type AddDocumentFileCommand = {
    documentId?: string;
    title?: string | null;
    order?: number | null;
    isPrimary?: boolean;
    totalPages?: number | null;
    fileId?: string;
    coverFileId?: string | null;
};

export type AuthorDetailDto = {
    id?: string;
    fullName?: string;
    description?: string;
    documentCount?: number;
};

export type AuthorDto = {
    id?: string;
    fullName?: string;
};

export type AuthorInput = {
    fullName?: string;
    description?: string | null;
};

export type AuthorListDto = {
    id?: string;
    fullName?: string;
    description?: string;
};

export type BanUserCommand = {
    userId?: string;
    banUntil?: string | null;
};

export type ChangePasswordCommand = {
    currentPassword?: string;
    newPassword?: string;
};

export type ChangeUsernameCommand = {
    newUsername?: string;
    currentPassword?: string;
};

export type CommentDto = {
    id?: string;
    documentId?: string;
    documentFileId?: string;
    parentId?: string | null;
    content?: string;
    authorName?: string;
    authorAvatarUrl?: string | null;
    createdById?: string;
    status?: ContentStatus;
    replyCount?: number;
    createdAt?: string;
    updatedAt?: string | null;
};

export type ContentStatus = number;

export type ConversationDetailDto = {
    id?: string;
    conversationName?: string;
    tags?: Array<TagDto>;
    conversationType?: ConversitionType;
    visibility?: ConversationVisibility;
    conversationStatus?: ConversationStatus;
    isSuggestedByAI?: boolean;
    isAllowMemberPin?: boolean;
    subject?: SubjectDto;
    avatarUrl?: string | null;
    members?: Array<ConversationMemberDto>;
    messageCount?: number;
    lastMessageId?: string | null;
    createdById?: string;
    createdAt?: string;
    updatedAt?: string | null;
};

export type ConversationDto = {
    id?: string;
    conversationName?: string;
    tags?: Array<TagDto>;
    conversationType?: ConversitionType;
    visibility?: ConversationVisibility;
    conversationStatus?: ConversationStatus;
    isSuggestedByAI?: boolean;
    isAllowMemberPin?: boolean;
    subject?: SubjectDto;
    avatarUrl?: string | null;
    memberCount?: number;
    unreadCount?: number;
    lastMessageId?: string | null;
    createdById?: string;
    createdAt?: string;
    updatedAt?: string | null;
    isCurrentUserMember?: boolean | null;
    hasPendingJoinRequest?: boolean | null;
};

export type ConversationJoinRequestDto = {
    id?: string;
    conversationId?: string;
    conversationName?: string;
    content?: string;
    requesterName?: string;
    requesterAvatarUrl?: string | null;
    createdById?: string;
    status?: ContentStatus;
    reviewNote?: string | null;
    createdAt?: string;
};

export type ConversationMemberDto = {
    id?: string;
    userId?: string;
    userName?: string;
    userAvatarUrl?: string | null;
    roleType?: ConversationMemberRoleType;
    isMuted?: boolean;
    joinedAt?: string;
};

export type ConversationMemberRoleType = number;

export type ConversationRecommendationDto = {
    conversationId?: string;
    conversationName?: string;
    similarity?: number;
    rank?: number;
    subject?: SubjectDto;
    tags?: Array<TagDto>;
    avatarUrl?: string | null;
    memberCount?: number;
    isCurrentUserMember?: boolean | null;
};

export type ConversationStatus = number;

export type ConversationVisibility = number;

export type ConversitionType = number;

export type CreateAuthorCommand = {
    fullName?: string;
    description?: string | null;
};

export type CreateCommentCommand = {
    documentFileId?: string;
    parentId?: string | null;
    content?: string;
};

export type CreateConversationCommand = {
    conversationName?: string;
    tagIds?: Array<string> | null;
    tagNames?: Array<string> | null;
    conversationType?: ConversitionType;
    visibility?: ConversationVisibility;
    subjectId?: string | null;
    isSuggestedByAI?: boolean;
    isAllowMemberPin?: boolean;
    avatarUrl?: string | null;
};

export type CreateConversationJoinRequestCommand = {
    conversationId?: string;
    content?: string;
};

export type CreateDocumentCommand = {
    documentName?: string;
    description?: string;
    subjectId?: string | null;
    typeId?: string;
    tagIds?: Array<string> | null;
    tagNames?: Array<string> | null;
    authorIds?: Array<string> | null;
    authors?: Array<AuthorInput> | null;
    visibility?: VisibilityStatus;
    coverFileId?: string | null;
};

export type CreateDocumentReviewCommand = {
    documentFileId?: string;
    documentReviewType?: DocumentReviewType;
};

export type CreateEventCommand = {
    title?: string;
    shortDescription?: string | null;
    content?: string | null;
    imageUrl?: string | null;
    redirectUrl?: string | null;
    startAt?: string;
    endAt?: string;
    isActive?: boolean;
    priority?: number;
};

export type CreateFacultyCommand = {
    facultyName?: string;
    facultyCode?: string;
    logo?: string | null;
};

export type CreateMajorCommand = {
    facultyId?: string;
    majorName?: string;
    majorCode?: string;
};

export type CreateMessageCommand = {
    conversationId?: string;
    parentId?: string | null;
    content?: string;
    fileIds?: Array<string> | null;
};

export type CreateNotificationCommand = {
    objectId?: string;
    title?: string;
    content?: string;
    link?: string;
    isGlobal?: boolean;
    expiredAt?: string;
    notificationType?: NotificationType;
    notificationPriorityType?: NotificationPriorityType;
    recipientIds?: Array<string> | null;
};

export type CreateReportCommand = {
    documentFileId?: string | null;
    commentId?: string | null;
    content?: string;
};

export type CreateSubjectCommand = {
    subjectName?: string;
    subjectCode?: string;
    majorIds?: Array<string>;
};

export type CreateTagCommand = {
    tagName?: string;
};

export type CreateTypeCommand = {
    typeName?: string;
};

export type DocumentDetailDto = {
    id?: string;
    documentName?: string;
    description?: string;
    visibility?: VisibilityStatus;
    subject?: SubjectDto;
    type?: TypeDto;
    tags?: Array<TagDto>;
    authors?: Array<AuthorDto>;
    coverFileId?: string | null;
    files?: Array<DocumentFileDto>;
    commentCount?: number;
    usefulCount?: number;
    notUsefulCount?: number;
    createdById?: string;
    createdAt?: string;
    updatedAt?: string | null;
};

export type DocumentDto = {
    id?: string;
    documentName?: string;
    description?: string;
    visibility?: VisibilityStatus;
    subject?: SubjectDto;
    type?: TypeDto;
    tags?: Array<TagDto>;
    authors?: Array<AuthorDto>;
    thumbnailFileId?: string | null;
    fileCount?: number;
    commentCount?: number;
    usefulCount?: number;
    notUsefulCount?: number;
    createdById?: string;
    createdAt?: string;
};

export type DocumentFileDto = {
    id?: string;
    fileId?: string;
    fileSize?: number;
    mimeType?: string;
    title?: string | null;
    order?: number | null;
    isPrimary?: boolean;
    totalPages?: number | null;
    coverFileId?: string | null;
    status?: ContentStatus;
    commentCount?: number;
    usefulCount?: number;
    notUsefulCount?: number;
    progress?: DocumentProgressDto;
};

export type DocumentProgressDto = {
    documentFileId?: string;
    lastPage?: number;
    totalPages?: number | null;
    lastAccessedAt?: string | null;
} | null;

export type DocumentProgressDto2 = {
    documentFileId?: string;
    lastPage?: number;
    totalPages?: number | null;
    lastAccessedAt?: string | null;
};

export type DocumentReviewDto = {
    id?: string;
    documentId?: string;
    documentFileId?: string;
    documentReviewType?: DocumentReviewType;
    createdById?: string;
    createdAt?: string;
    updatedAt?: string | null;
};

export type DocumentReviewType = number;

export type EventDto = {
    id?: string;
    title?: string;
    shortDescription?: string | null;
    content?: string | null;
    imageUrl?: string | null;
    redirectUrl?: string | null;
    startAt?: string;
    endAt?: string;
    isActive?: boolean;
    priority?: number;
};

export type FacultyDetailDto = {
    id?: string;
    facultyName?: string;
    facultyCode?: string;
    logo?: string;
    majorCount?: number;
};

export type FacultyDto = {
    id?: string;
    facultyName?: string;
    facultyCode?: string;
    logo?: string;
} | null;

export type FacultyDto2 = {
    id?: string;
    facultyName?: string;
    facultyCode?: string;
    logo?: string;
};

export type FileDto = {
    id?: string;
    fileSize?: number;
    mimeType?: string;
};

export type ForgotPasswordCommand = {
    email?: string;
};

export type Gender = number;

export type GetConversationRecommendationsResponse = {
    recommendations?: Array<ConversationRecommendationDto>;
    totalProcessed?: number;
    processingTimeMs?: number;
};

export type GetOnlineMembersResponse = {
    conversationId?: string;
    onlineUserIds?: Array<string>;
};

export type LoginCommand = {
    emailOrUsername?: string;
    password?: string;
};

export type LoginResponse = {
    id?: string;
    email?: string;
    fullName?: string;
    username?: string | null;
    avatarUrl?: string | null;
    accessToken?: string;
    refreshToken?: string;
};

export type LoginWithMicrosoftCommand = {
    idToken?: string;
};

export type LoginWithMicrosoftResponse = {
    id?: string;
    email?: string;
    fullName?: string;
    username?: string | null;
    avatarUrl?: string | null;
    accessToken?: string;
    refreshToken?: string;
};

export type MajorDetailDto = {
    id?: string;
    majorName?: string;
    majorCode?: string;
    faculty?: FacultyDto;
    subjectCount?: number;
};

export type MajorDto = {
    id?: string;
    majorName?: string;
    majorCode?: string;
    faculty?: FacultyDto;
} | null;

export type MajorDto2 = {
    id?: string;
    majorName?: string;
    majorCode?: string;
    faculty?: FacultyDto;
};

export type ManageTrustScoreCommand = {
    userId?: string;
    trustScore?: number;
    reason?: string | null;
};

export type MessageDto = {
    id?: string;
    conversationId?: string;
    parentId?: string | null;
    content?: string;
    isEdit?: boolean;
    isPined?: boolean;
    type?: NullableOfMessageType;
    createdById?: string;
    senderName?: string;
    senderAvatarUrl?: string | null;
    files?: Array<MessageFileDto>;
    createdAt?: string;
    updatedAt?: string | null;
};

export type MessageFileDto = {
    fileId?: string;
    fileSize?: number;
    mimeType?: string;
};

export type NotificationDto = {
    id?: string;
    objectId?: string;
    title?: string;
    content?: string;
    link?: string;
    isGlobal?: boolean;
    expiredAt?: string;
    notificationType?: NotificationType;
    notificationPriorityType?: NotificationPriorityType;
    isRead?: boolean;
    readAt?: string | null;
    createdAt?: string;
    receivedAt?: string | null;
};

export type NotificationPriorityType = number;

export type NotificationType = number;

export type NullableOfConversationStatus = number | null;

export type NullableOfConversationVisibility = number | null;

export type NullableOfConversitionType = number | null;

export type NullableOfGender = number | null;

export type NullableOfMessageType = number | null;

export type NullableOfVisibilityStatus = number | null;

export type PagedResponseOfAuthorListDto = {
    items?: Array<AuthorListDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfCommentDto = {
    items?: Array<CommentDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfConversationDto = {
    items?: Array<ConversationDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfConversationJoinRequestDto = {
    items?: Array<ConversationJoinRequestDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfDocumentDto = {
    items?: Array<DocumentDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfFacultyDto = {
    items?: Array<FacultyDto2>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfMajorDto = {
    items?: Array<MajorDto2>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfMessageDto = {
    items?: Array<MessageDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfNotificationDto = {
    items?: Array<NotificationDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfReadingHistoryItemDto = {
    items?: Array<ReadingHistoryItemDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfReportDto = {
    items?: Array<ReportDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfSubjectDto = {
    items?: Array<SubjectDto2>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfTagDto = {
    items?: Array<TagDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfTypeDto = {
    items?: Array<TypeDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PagedResponseOfUserDto = {
    items?: Array<UserDto>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PinMessageCommand = {
    id?: string;
    conversationId?: string;
    isPined?: boolean;
};

export type ProfileDto = {
    id?: string;
    email?: string;
    username?: string | null;
    fullName?: string;
    emailConfirmed?: boolean;
    avatarUrl?: string | null;
    introduction?: string | null;
    trustScore?: number;
    trustLevel?: string;
    gender?: Gender;
    roles?: Array<string>;
    major?: MajorDto;
    createdAt?: string;
};

export type ReadingHistoryItemDto = {
    documentId?: string;
    documentName?: string;
    documentFileId?: string | null;
    fileTitle?: string | null;
    lastPage?: number;
    totalPages?: number | null;
    lastAccessedAt?: string | null;
    coverFileId?: string | null;
    subjectName?: string | null;
};

export type RefreshTokenCommand = {
    [key: string]: unknown;
};

export type RefreshTokenResponse = {
    [key: string]: unknown;
};

export type ReportDto = {
    id?: string;
    documentFileId?: string | null;
    commentId?: string | null;
    content?: string;
    reporterName?: string;
    reporterAvatarUrl?: string | null;
    createdById?: string;
    status?: ContentStatus;
    createdAt?: string;
};

export type ResetPasswordCommand = {
    email?: string;
    token?: string;
    newPassword?: string;
};

export type ReviewConversationJoinRequestCommand = {
    joinRequestId?: string;
    status?: ContentStatus;
    reviewNote?: string | null;
};

export type ReviewDocumentFileCommand = {
    documentFileId?: string;
    status?: ContentStatus;
};

export type ReviewReportCommand = {
    reportId?: string;
    status?: ContentStatus;
    reviewNote?: string | null;
};

export type SubjectDetailDto = {
    id?: string;
    subjectName?: string;
    subjectCode?: string;
    majors?: Array<MajorDto2>;
    documentCount?: number;
};

export type SubjectDto = {
    id?: string;
    subjectName?: string;
    subjectCode?: string;
    majors?: Array<MajorDto2>;
} | null;

export type SubjectDto2 = {
    id?: string;
    subjectName?: string;
    subjectCode?: string;
    majors?: Array<MajorDto2>;
};

export type TagDetailDto = {
    id?: string;
    tagName?: string;
    documentCount?: number;
};

export type TagDto = {
    id?: string;
    tagName?: string;
};

export type TypeDetailDto = {
    id?: string;
    typeName?: string;
    documentCount?: number;
};

export type TypeDto = {
    id?: string;
    typeName?: string;
};

export type Unit = {
    [key: string]: unknown;
};

export type UnreadCountDto = {
    unreadCount?: number;
};

export type UpdateAuthorCommand = {
    id?: string;
    fullName?: string | null;
    description?: string | null;
};

export type UpdateCommentCommand = {
    id?: string;
    content?: string;
};

export type UpdateConversationCommand = {
    id?: string;
    conversationName?: string | null;
    tagIds?: Array<string> | null;
    tagNames?: Array<string> | null;
    conversationType?: NullableOfConversitionType;
    visibility?: NullableOfConversationVisibility;
    conversationStatus?: NullableOfConversationStatus;
    subjectId?: string | null;
    isAllowMemberPin?: boolean | null;
    avatarUrl?: string | null;
};

export type UpdateDocumentCommand = {
    id?: string;
    documentName?: string | null;
    description?: string | null;
    subjectId?: string | null;
    typeId?: string | null;
    tagIds?: Array<string> | null;
    authorIds?: Array<string> | null;
    authors?: Array<AuthorInput> | null;
    visibility?: NullableOfVisibilityStatus;
    fileIdsToRemove?: Array<string> | null;
    coverFileId?: string | null;
};

export type UpdateDocumentFileCommand = {
    documentId?: string;
    documentFileId?: string;
    title?: string | null;
    order?: number | null;
    isPrimary?: boolean | null;
    coverFileId?: string | null;
};

export type UpdateDocumentProgressCommand = {
    documentFileId?: string;
    lastPage?: number;
};

export type UpdateEventCommand = {
    id?: string;
    title?: string;
    shortDescription?: string | null;
    content?: string | null;
    imageUrl?: string | null;
    redirectUrl?: string | null;
    startAt?: string;
    endAt?: string;
    isActive?: boolean;
    priority?: number;
};

export type UpdateFacultyCommand = {
    id?: string;
    facultyName?: string;
    facultyCode?: string;
    logo?: string | null;
};

export type UpdateMajorCommand = {
    id?: string;
    facultyId?: string;
    majorName?: string;
    majorCode?: string;
};

export type UpdateMemberRoleCommand = {
    conversationId?: string;
    memberId?: string;
    roleType?: ConversationMemberRoleType;
};

export type UpdateMessageCommand = {
    id?: string;
    conversationId?: string;
    content?: string;
};

export type UpdateNotificationRequest = {
    title?: string;
    content?: string;
    link?: string | null;
    expiredAt?: string;
    notificationType?: NotificationType;
    notificationPriorityType?: NotificationPriorityType;
};

export type UpdateProfileCommand = {
    fullName?: string | null;
    introduction?: string | null;
    avatarUrl?: string | null;
    majorId?: string | null;
    gender?: NullableOfGender;
};

export type UpdateSubjectCommand = {
    id?: string;
    subjectName?: string;
    subjectCode?: string;
    majorIds?: Array<string>;
};

export type UpdateTagCommand = {
    id?: string;
    tagName?: string;
};

export type UpdateTypeCommand = {
    id?: string;
    typeName?: string;
};

export type UpdateUserCommand = {
    userId?: string;
    fullName?: string | null;
    email?: string | null;
    username?: string | null;
    introduction?: string | null;
    avatarUrl?: string | null;
    majorId?: string | null;
    gender?: NullableOfGender;
    emailConfirmed?: boolean | null;
    roles?: Array<string> | null;
};

export type UserDto = {
    id?: string;
    email?: string;
    username?: string | null;
    fullName?: string;
    emailConfirmed?: boolean;
    avatarUrl?: string | null;
    introduction?: string | null;
    trustScore?: number;
    trustLevel?: string;
    gender?: Gender;
    isSuggest?: boolean;
    roles?: Array<string>;
    major?: MajorDto;
    createdAt?: string;
    updatedAt?: string | null;
    lastLoginAt?: string | null;
    isDeleted?: boolean;
    deletedAt?: string | null;
    deletedById?: string | null;
    lockoutEnabled?: boolean;
    lockoutEnd?: string | null;
};

export type UserTrustHistoryDto = {
    id?: string;
    userId?: string;
    score?: number;
    reason?: string;
    createdAt?: string;
};

export type VisibilityStatus = number;

export type GetApiAccountProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/profile';
};

export type GetApiAccountProfileResponses = {
    /**
     * OK
     */
    200: ProfileDto;
};

export type GetApiAccountProfileResponse = GetApiAccountProfileResponses[keyof GetApiAccountProfileResponses];

export type PutApiAccountProfileData = {
    body: UpdateProfileCommand;
    path?: never;
    query?: never;
    url: '/api/Account/profile';
};

export type PutApiAccountProfileResponses = {
    /**
     * OK
     */
    200: ProfileDto;
};

export type PutApiAccountProfileResponse = PutApiAccountProfileResponses[keyof PutApiAccountProfileResponses];

export type GetApiAccountProfileByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/Account/profile/{userId}';
};

export type GetApiAccountProfileByUserIdResponses = {
    /**
     * OK
     */
    200: ProfileDto;
};

export type GetApiAccountProfileByUserIdResponse = GetApiAccountProfileByUserIdResponses[keyof GetApiAccountProfileByUserIdResponses];

export type PostApiAuthLoginData = {
    body: LoginCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthLoginMicrosoftData = {
    body: LoginWithMicrosoftCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/login/microsoft';
};

export type PostApiAuthLoginMicrosoftResponses = {
    /**
     * OK
     */
    200: LoginWithMicrosoftResponse;
};

export type PostApiAuthLoginMicrosoftResponse = PostApiAuthLoginMicrosoftResponses[keyof PostApiAuthLoginMicrosoftResponses];

export type PostApiAuthRefreshTokenData = {
    body: RefreshTokenCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh-token';
};

export type PostApiAuthRefreshTokenResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponse;
};

export type PostApiAuthRefreshTokenResponse = PostApiAuthRefreshTokenResponses[keyof PostApiAuthRefreshTokenResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthForgotPasswordData = {
    body: ForgotPasswordCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/forgot-password';
};

export type PostApiAuthForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthResetPasswordData = {
    body: ResetPasswordCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/reset-password';
};

export type PostApiAuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthChangePasswordData = {
    body: ChangePasswordCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/change-password';
};

export type PostApiAuthChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthChangeUsernameData = {
    body: ChangeUsernameCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/change-username';
};

export type PostApiAuthChangeUsernameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthorData = {
    body?: never;
    path?: never;
    query?: {
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Author';
};

export type GetApiAuthorResponses = {
    /**
     * OK
     */
    200: PagedResponseOfAuthorListDto;
};

export type GetApiAuthorResponse = GetApiAuthorResponses[keyof GetApiAuthorResponses];

export type PostApiAuthorData = {
    body: CreateAuthorCommand;
    path?: never;
    query?: never;
    url: '/api/Author';
};

export type PostApiAuthorResponses = {
    /**
     * OK
     */
    200: AuthorDetailDto;
};

export type PostApiAuthorResponse = PostApiAuthorResponses[keyof PostApiAuthorResponses];

export type DeleteApiAuthorByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Author/{id}';
};

export type DeleteApiAuthorByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthorByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Author/{id}';
};

export type GetApiAuthorByIdResponses = {
    /**
     * OK
     */
    200: AuthorDetailDto;
};

export type GetApiAuthorByIdResponse = GetApiAuthorByIdResponses[keyof GetApiAuthorByIdResponses];

export type PutApiAuthorByIdData = {
    body: UpdateAuthorCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Author/{id}';
};

export type PutApiAuthorByIdResponses = {
    /**
     * OK
     */
    200: AuthorDetailDto;
};

export type PutApiAuthorByIdResponse = PutApiAuthorByIdResponses[keyof PutApiAuthorByIdResponses];

export type GetApiCommentData = {
    body?: never;
    path?: never;
    query?: {
        DocumentFileId?: string;
        ParentId?: string;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Comment';
};

export type GetApiCommentResponses = {
    /**
     * OK
     */
    200: PagedResponseOfCommentDto;
};

export type GetApiCommentResponse = GetApiCommentResponses[keyof GetApiCommentResponses];

export type PostApiCommentData = {
    body: CreateCommentCommand;
    path?: never;
    query?: never;
    url: '/api/Comment';
};

export type PostApiCommentResponses = {
    /**
     * OK
     */
    200: CommentDto;
};

export type PostApiCommentResponse = PostApiCommentResponses[keyof PostApiCommentResponses];

export type GetApiCommentDocumentData = {
    body?: never;
    path?: never;
    query?: {
        DocumentId?: string;
        ParentId?: string;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Comment/document';
};

export type GetApiCommentDocumentResponses = {
    /**
     * OK
     */
    200: PagedResponseOfCommentDto;
};

export type GetApiCommentDocumentResponse = GetApiCommentDocumentResponses[keyof GetApiCommentDocumentResponses];

export type DeleteApiCommentByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Comment/{id}';
};

export type DeleteApiCommentByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiCommentByIdData = {
    body: UpdateCommentCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Comment/{id}';
};

export type PutApiCommentByIdResponses = {
    /**
     * OK
     */
    200: CommentDto;
};

export type PutApiCommentByIdResponse = PutApiCommentByIdResponses[keyof PutApiCommentByIdResponses];

export type GetApiConversationData = {
    body?: never;
    path?: never;
    query?: {
        SubjectId?: string;
        TagId?: string;
        ConversationType?: string;
        Visibility?: string;
        ConversationStatus?: string;
        CreatedById?: string;
        MemberId?: string;
        SearchTerm?: string;
        SortBy?: string;
        SortDescending?: boolean;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Conversation';
};

export type GetApiConversationResponses = {
    /**
     * OK
     */
    200: PagedResponseOfConversationDto;
};

export type GetApiConversationResponse = GetApiConversationResponses[keyof GetApiConversationResponses];

export type PostApiConversationData = {
    body: CreateConversationCommand;
    path?: never;
    query?: never;
    url: '/api/Conversation';
};

export type PostApiConversationResponses = {
    /**
     * OK
     */
    200: ConversationDetailDto;
};

export type PostApiConversationResponse = PostApiConversationResponses[keyof PostApiConversationResponses];

export type DeleteApiConversationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Conversation/{id}';
};

export type DeleteApiConversationByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiConversationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Conversation/{id}';
};

export type GetApiConversationByIdResponses = {
    /**
     * OK
     */
    200: ConversationDetailDto;
};

export type GetApiConversationByIdResponse = GetApiConversationByIdResponses[keyof GetApiConversationByIdResponses];

export type PutApiConversationByIdData = {
    body: UpdateConversationCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Conversation/{id}';
};

export type PutApiConversationByIdResponses = {
    /**
     * OK
     */
    200: ConversationDetailDto;
};

export type PutApiConversationByIdResponse = PutApiConversationByIdResponses[keyof PutApiConversationByIdResponses];

export type PostApiConversationByIdJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Conversation/{id}/join';
};

export type PostApiConversationByIdJoinResponses = {
    /**
     * OK
     */
    200: ConversationDetailDto;
};

export type PostApiConversationByIdJoinResponse = PostApiConversationByIdJoinResponses[keyof PostApiConversationByIdJoinResponses];

export type PostApiConversationByIdLeaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Conversation/{id}/leave';
};

export type PostApiConversationByIdLeaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiConversationByConversationIdOnlineMembersData = {
    body?: never;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/Conversation/{conversationId}/online-members';
};

export type GetApiConversationByConversationIdOnlineMembersResponses = {
    /**
     * OK
     */
    200: GetOnlineMembersResponse;
};

export type GetApiConversationByConversationIdOnlineMembersResponse = GetApiConversationByConversationIdOnlineMembersResponses[keyof GetApiConversationByConversationIdOnlineMembersResponses];

export type PutApiConversationByIdMembersByMemberIdRoleData = {
    body: UpdateMemberRoleCommand;
    path: {
        id: string;
        memberId: string;
    };
    query?: never;
    url: '/api/Conversation/{id}/members/{memberId}/role';
};

export type PutApiConversationByIdMembersByMemberIdRoleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiConversationRecommendationsData = {
    body?: never;
    path?: never;
    query?: {
        topK?: number;
        minSimilarity?: number;
    };
    url: '/api/Conversation/recommendations';
};

export type GetApiConversationRecommendationsResponses = {
    /**
     * OK
     */
    200: GetConversationRecommendationsResponse;
};

export type GetApiConversationRecommendationsResponse = GetApiConversationRecommendationsResponses[keyof GetApiConversationRecommendationsResponses];

export type GetApiConversationJoinRequestData = {
    body?: never;
    path?: never;
    query?: {
        ConversationId?: string;
        CreatedById?: string;
        Status?: string;
        SearchTerm?: string;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/ConversationJoinRequest';
};

export type GetApiConversationJoinRequestResponses = {
    /**
     * OK
     */
    200: PagedResponseOfConversationJoinRequestDto;
};

export type GetApiConversationJoinRequestResponse = GetApiConversationJoinRequestResponses[keyof GetApiConversationJoinRequestResponses];

export type PostApiConversationJoinRequestData = {
    body: CreateConversationJoinRequestCommand;
    path?: never;
    query?: never;
    url: '/api/ConversationJoinRequest';
};

export type PostApiConversationJoinRequestResponses = {
    /**
     * OK
     */
    200: ConversationJoinRequestDto;
};

export type PostApiConversationJoinRequestResponse = PostApiConversationJoinRequestResponses[keyof PostApiConversationJoinRequestResponses];

export type PostApiConversationJoinRequestByIdReviewData = {
    body: ReviewConversationJoinRequestCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ConversationJoinRequest/{id}/review';
};

export type PostApiConversationJoinRequestByIdReviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiDocumentData = {
    body?: never;
    path?: never;
    query?: {
        SubjectId?: string;
        TypeId?: string;
        TagIds?: Array<string>;
        MajorId?: string;
        AuthorId?: string;
        SearchTerm?: string;
        Visibility?: string;
        SortBy?: string;
        SortDescending?: boolean;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Document';
};

export type GetApiDocumentResponses = {
    /**
     * OK
     */
    200: PagedResponseOfDocumentDto;
};

export type GetApiDocumentResponse = GetApiDocumentResponses[keyof GetApiDocumentResponses];

export type PostApiDocumentData = {
    body: CreateDocumentCommand;
    path?: never;
    query?: never;
    url: '/api/Document';
};

export type PostApiDocumentResponses = {
    /**
     * OK
     */
    200: DocumentDetailDto;
};

export type PostApiDocumentResponse = PostApiDocumentResponses[keyof PostApiDocumentResponses];

export type GetApiDocumentMyData = {
    body?: never;
    path?: never;
    query?: {
        SubjectId?: string;
        TypeId?: string;
        TagId?: string;
        SearchTerm?: string;
        Visibility?: string;
        FileStatus?: string;
        SortBy?: string;
        SortDescending?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Document/my';
};

export type GetApiDocumentMyResponses = {
    /**
     * OK
     */
    200: PagedResponseOfDocumentDto;
};

export type GetApiDocumentMyResponse = GetApiDocumentMyResponses[keyof GetApiDocumentMyResponses];

export type DeleteApiDocumentByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Document/{id}';
};

export type DeleteApiDocumentByIdResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type DeleteApiDocumentByIdResponse = DeleteApiDocumentByIdResponses[keyof DeleteApiDocumentByIdResponses];

export type GetApiDocumentByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Document/{id}';
};

export type GetApiDocumentByIdResponses = {
    /**
     * OK
     */
    200: DocumentDetailDto;
};

export type GetApiDocumentByIdResponse = GetApiDocumentByIdResponses[keyof GetApiDocumentByIdResponses];

export type PutApiDocumentByIdData = {
    body: UpdateDocumentCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Document/{id}';
};

export type PutApiDocumentByIdResponses = {
    /**
     * OK
     */
    200: DocumentDetailDto;
};

export type PutApiDocumentByIdResponse = PutApiDocumentByIdResponses[keyof PutApiDocumentByIdResponses];

export type PostApiDocumentByIdFilesData = {
    body: AddDocumentFileCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Document/{id}/files';
};

export type PostApiDocumentByIdFilesResponses = {
    /**
     * OK
     */
    200: DocumentDetailDto;
};

export type PostApiDocumentByIdFilesResponse = PostApiDocumentByIdFilesResponses[keyof PostApiDocumentByIdFilesResponses];

export type DeleteApiDocumentByDocumentIdFilesByFileIdData = {
    body?: never;
    path: {
        documentId: string;
        fileId: string;
    };
    query?: never;
    url: '/api/Document/{documentId}/files/{fileId}';
};

export type DeleteApiDocumentByDocumentIdFilesByFileIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiDocumentByDocumentIdFilesByFileIdData = {
    body: UpdateDocumentFileCommand;
    path: {
        documentId: string;
        fileId: string;
    };
    query?: never;
    url: '/api/Document/{documentId}/files/{fileId}';
};

export type PutApiDocumentByDocumentIdFilesByFileIdResponses = {
    /**
     * OK
     */
    200: DocumentDetailDto;
};

export type PutApiDocumentByDocumentIdFilesByFileIdResponse = PutApiDocumentByDocumentIdFilesByFileIdResponses[keyof PutApiDocumentByDocumentIdFilesByFileIdResponses];

export type GetApiDocumentReadingHistoryData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Document/reading-history';
};

export type GetApiDocumentReadingHistoryResponses = {
    /**
     * OK
     */
    200: PagedResponseOfReadingHistoryItemDto;
};

export type GetApiDocumentReadingHistoryResponse = GetApiDocumentReadingHistoryResponses[keyof GetApiDocumentReadingHistoryResponses];

export type GetApiDocumentFilesByFileIdProgressData = {
    body?: never;
    path: {
        fileId: string;
    };
    query?: never;
    url: '/api/Document/files/{fileId}/progress';
};

export type GetApiDocumentFilesByFileIdProgressResponses = {
    /**
     * OK
     */
    200: DocumentProgressDto2;
};

export type GetApiDocumentFilesByFileIdProgressResponse = GetApiDocumentFilesByFileIdProgressResponses[keyof GetApiDocumentFilesByFileIdProgressResponses];

export type PutApiDocumentFilesByFileIdProgressData = {
    body: UpdateDocumentProgressCommand;
    path: {
        fileId: string;
    };
    query?: never;
    url: '/api/Document/files/{fileId}/progress';
};

export type PutApiDocumentFilesByFileIdProgressResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiDocumentFilesByFileIdReviewData = {
    body: ReviewDocumentFileCommand;
    path: {
        fileId: string;
    };
    query?: never;
    url: '/api/Document/files/{fileId}/review';
};

export type PostApiDocumentFilesByFileIdReviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiDocumentReviewData = {
    body: CreateDocumentReviewCommand;
    path?: never;
    query?: never;
    url: '/api/DocumentReview';
};

export type PostApiDocumentReviewResponses = {
    /**
     * OK
     */
    200: DocumentReviewDto;
};

export type PostApiDocumentReviewResponse = PostApiDocumentReviewResponses[keyof PostApiDocumentReviewResponses];

export type GetApiEventActiveData = {
    body?: never;
    path?: never;
    query?: {
        Take?: number;
    };
    url: '/api/Event/active';
};

export type GetApiEventActiveResponses = {
    /**
     * OK
     */
    200: Array<EventDto>;
};

export type GetApiEventActiveResponse = GetApiEventActiveResponses[keyof GetApiEventActiveResponses];

export type PostApiEventData = {
    body: CreateEventCommand;
    path?: never;
    query?: never;
    url: '/api/Event';
};

export type PostApiEventResponses = {
    /**
     * OK
     */
    200: EventDto;
};

export type PostApiEventResponse = PostApiEventResponses[keyof PostApiEventResponses];

export type DeleteApiEventByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Event/{id}';
};

export type DeleteApiEventByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiEventByIdData = {
    body: UpdateEventCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Event/{id}';
};

export type PutApiEventByIdResponses = {
    /**
     * OK
     */
    200: EventDto;
};

export type PutApiEventByIdResponse = PutApiEventByIdResponses[keyof PutApiEventByIdResponses];

export type GetApiFacultyData = {
    body?: never;
    path?: never;
    query?: {
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Faculty';
};

export type GetApiFacultyResponses = {
    /**
     * OK
     */
    200: PagedResponseOfFacultyDto;
};

export type GetApiFacultyResponse = GetApiFacultyResponses[keyof GetApiFacultyResponses];

export type PostApiFacultyData = {
    body: CreateFacultyCommand;
    path?: never;
    query?: never;
    url: '/api/Faculty';
};

export type PostApiFacultyResponses = {
    /**
     * OK
     */
    200: FacultyDetailDto;
};

export type PostApiFacultyResponse = PostApiFacultyResponses[keyof PostApiFacultyResponses];

export type DeleteApiFacultyByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Faculty/{id}';
};

export type DeleteApiFacultyByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiFacultyByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Faculty/{id}';
};

export type GetApiFacultyByIdResponses = {
    /**
     * OK
     */
    200: FacultyDetailDto;
};

export type GetApiFacultyByIdResponse = GetApiFacultyByIdResponses[keyof GetApiFacultyByIdResponses];

export type PutApiFacultyByIdData = {
    body: UpdateFacultyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Faculty/{id}';
};

export type PutApiFacultyByIdResponses = {
    /**
     * OK
     */
    200: FacultyDetailDto;
};

export type PutApiFacultyByIdResponse = PutApiFacultyByIdResponses[keyof PutApiFacultyByIdResponses];

export type PostApiFileData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: {
        category?: string;
    };
    url: '/api/File';
};

export type PostApiFileResponses = {
    /**
     * OK
     */
    200: FileDto;
};

export type PostApiFileResponse = PostApiFileResponses[keyof PostApiFileResponses];

export type GetApiFileByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/File/{id}';
};

export type GetApiFileByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Health';
};

export type GetApiHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMajorData = {
    body?: never;
    path?: never;
    query?: {
        FacultyId?: string;
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Major';
};

export type GetApiMajorResponses = {
    /**
     * OK
     */
    200: PagedResponseOfMajorDto;
};

export type GetApiMajorResponse = GetApiMajorResponses[keyof GetApiMajorResponses];

export type PostApiMajorData = {
    body: CreateMajorCommand;
    path?: never;
    query?: never;
    url: '/api/Major';
};

export type PostApiMajorResponses = {
    /**
     * OK
     */
    200: MajorDetailDto;
};

export type PostApiMajorResponse = PostApiMajorResponses[keyof PostApiMajorResponses];

export type DeleteApiMajorByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Major/{id}';
};

export type DeleteApiMajorByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMajorByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Major/{id}';
};

export type GetApiMajorByIdResponses = {
    /**
     * OK
     */
    200: MajorDetailDto;
};

export type GetApiMajorByIdResponse = GetApiMajorByIdResponses[keyof GetApiMajorByIdResponses];

export type PutApiMajorByIdData = {
    body: UpdateMajorCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Major/{id}';
};

export type PutApiMajorByIdResponses = {
    /**
     * OK
     */
    200: MajorDetailDto;
};

export type PutApiMajorByIdResponse = PutApiMajorByIdResponses[keyof PutApiMajorByIdResponses];

export type GetApiConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        conversationId: string;
    };
    query?: {
        ConversationId?: string;
        ParentId?: string;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/conversations/{conversationId}/messages';
};

export type GetApiConversationsByConversationIdMessagesResponses = {
    /**
     * OK
     */
    200: PagedResponseOfMessageDto;
};

export type GetApiConversationsByConversationIdMessagesResponse = GetApiConversationsByConversationIdMessagesResponses[keyof GetApiConversationsByConversationIdMessagesResponses];

export type PostApiConversationsByConversationIdMessagesData = {
    body: CreateMessageCommand;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/conversations/{conversationId}/messages';
};

export type PostApiConversationsByConversationIdMessagesResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PostApiConversationsByConversationIdMessagesResponse = PostApiConversationsByConversationIdMessagesResponses[keyof PostApiConversationsByConversationIdMessagesResponses];

export type DeleteApiConversationsByConversationIdMessagesByIdData = {
    body?: never;
    path: {
        conversationId: string;
        id: string;
    };
    query?: never;
    url: '/api/conversations/{conversationId}/messages/{id}';
};

export type DeleteApiConversationsByConversationIdMessagesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiConversationsByConversationIdMessagesByIdData = {
    body: UpdateMessageCommand;
    path: {
        conversationId: string;
        id: string;
    };
    query?: never;
    url: '/api/conversations/{conversationId}/messages/{id}';
};

export type PutApiConversationsByConversationIdMessagesByIdResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PutApiConversationsByConversationIdMessagesByIdResponse = PutApiConversationsByConversationIdMessagesByIdResponses[keyof PutApiConversationsByConversationIdMessagesByIdResponses];

export type PostApiConversationsByConversationIdMessagesByIdPinData = {
    body: PinMessageCommand;
    path: {
        conversationId: string;
        id: string;
    };
    query?: never;
    url: '/api/conversations/{conversationId}/messages/{id}/pin';
};

export type PostApiConversationsByConversationIdMessagesByIdPinResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiConversationsByConversationIdMessagesByIdMarkAsReadData = {
    body?: never;
    path: {
        conversationId: string;
        id: string;
    };
    query?: never;
    url: '/api/conversations/{conversationId}/messages/{id}/mark-as-read';
};

export type PostApiConversationsByConversationIdMessagesByIdMarkAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiNotificationData = {
    body?: never;
    path?: never;
    query?: {
        IsRead?: boolean;
        NotificationType?: string;
        NotificationPriorityType?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Notification';
};

export type GetApiNotificationResponses = {
    /**
     * OK
     */
    200: PagedResponseOfNotificationDto;
};

export type GetApiNotificationResponse = GetApiNotificationResponses[keyof GetApiNotificationResponses];

export type PostApiNotificationData = {
    body: CreateNotificationCommand;
    path?: never;
    query?: never;
    url: '/api/Notification';
};

export type PostApiNotificationResponses = {
    /**
     * OK
     */
    200: NotificationDto;
};

export type PostApiNotificationResponse = PostApiNotificationResponses[keyof PostApiNotificationResponses];

export type GetApiNotificationUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Notification/unread-count';
};

export type GetApiNotificationUnreadCountResponses = {
    /**
     * OK
     */
    200: UnreadCountDto;
};

export type GetApiNotificationUnreadCountResponse = GetApiNotificationUnreadCountResponses[keyof GetApiNotificationUnreadCountResponses];

export type PostApiNotificationByIdMarkAsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Notification/{id}/mark-as-read';
};

export type PostApiNotificationByIdMarkAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiNotificationMarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Notification/mark-all-as-read';
};

export type PostApiNotificationMarkAllAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiNotificationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Notification/{id}';
};

export type DeleteApiNotificationByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiNotificationByIdData = {
    body: UpdateNotificationRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Notification/{id}';
};

export type PutApiNotificationByIdResponses = {
    /**
     * OK
     */
    200: NotificationDto;
};

export type PutApiNotificationByIdResponse = PutApiNotificationByIdResponses[keyof PutApiNotificationByIdResponses];

export type GetApiReportData = {
    body?: never;
    path?: never;
    query?: {
        DocumentFileId?: string;
        CommentId?: string;
        Status?: string;
        SearchTerm?: string;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Report';
};

export type GetApiReportResponses = {
    /**
     * OK
     */
    200: PagedResponseOfReportDto;
};

export type GetApiReportResponse = GetApiReportResponses[keyof GetApiReportResponses];

export type PostApiReportData = {
    body: CreateReportCommand;
    path?: never;
    query?: never;
    url: '/api/Report';
};

export type PostApiReportResponses = {
    /**
     * OK
     */
    200: ReportDto;
};

export type PostApiReportResponse = PostApiReportResponses[keyof PostApiReportResponses];

export type PostApiReportByIdReviewData = {
    body: ReviewReportCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Report/{id}/review';
};

export type PostApiReportByIdReviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSubjectData = {
    body?: never;
    path?: never;
    query?: {
        MajorIds?: Array<string>;
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Subject';
};

export type GetApiSubjectResponses = {
    /**
     * OK
     */
    200: PagedResponseOfSubjectDto;
};

export type GetApiSubjectResponse = GetApiSubjectResponses[keyof GetApiSubjectResponses];

export type PostApiSubjectData = {
    body: CreateSubjectCommand;
    path?: never;
    query?: never;
    url: '/api/Subject';
};

export type PostApiSubjectResponses = {
    /**
     * OK
     */
    200: SubjectDetailDto;
};

export type PostApiSubjectResponse = PostApiSubjectResponses[keyof PostApiSubjectResponses];

export type DeleteApiSubjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Subject/{id}';
};

export type DeleteApiSubjectByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSubjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Subject/{id}';
};

export type GetApiSubjectByIdResponses = {
    /**
     * OK
     */
    200: SubjectDetailDto;
};

export type GetApiSubjectByIdResponse = GetApiSubjectByIdResponses[keyof GetApiSubjectByIdResponses];

export type PutApiSubjectByIdData = {
    body: UpdateSubjectCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Subject/{id}';
};

export type PutApiSubjectByIdResponses = {
    /**
     * OK
     */
    200: SubjectDetailDto;
};

export type PutApiSubjectByIdResponse = PutApiSubjectByIdResponses[keyof PutApiSubjectByIdResponses];

export type GetApiTagData = {
    body?: never;
    path?: never;
    query?: {
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Tag';
};

export type GetApiTagResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTagDto;
};

export type GetApiTagResponse = GetApiTagResponses[keyof GetApiTagResponses];

export type PostApiTagData = {
    body: CreateTagCommand;
    path?: never;
    query?: never;
    url: '/api/Tag';
};

export type PostApiTagResponses = {
    /**
     * OK
     */
    200: TagDetailDto;
};

export type PostApiTagResponse = PostApiTagResponses[keyof PostApiTagResponses];

export type DeleteApiTagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Tag/{id}';
};

export type DeleteApiTagByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Tag/{id}';
};

export type GetApiTagByIdResponses = {
    /**
     * OK
     */
    200: TagDetailDto;
};

export type GetApiTagByIdResponse = GetApiTagByIdResponses[keyof GetApiTagByIdResponses];

export type PutApiTagByIdData = {
    body: UpdateTagCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Tag/{id}';
};

export type PutApiTagByIdResponses = {
    /**
     * OK
     */
    200: TagDetailDto;
};

export type PutApiTagByIdResponse = PutApiTagByIdResponses[keyof PutApiTagByIdResponses];

export type GetApiTypeData = {
    body?: never;
    path?: never;
    query?: {
        SearchTerm?: string;
        IsDeleted?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/Type';
};

export type GetApiTypeResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTypeDto;
};

export type GetApiTypeResponse = GetApiTypeResponses[keyof GetApiTypeResponses];

export type PostApiTypeData = {
    body: CreateTypeCommand;
    path?: never;
    query?: never;
    url: '/api/Type';
};

export type PostApiTypeResponses = {
    /**
     * OK
     */
    200: TypeDetailDto;
};

export type PostApiTypeResponse = PostApiTypeResponses[keyof PostApiTypeResponses];

export type DeleteApiTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Type/{id}';
};

export type DeleteApiTypeByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Type/{id}';
};

export type GetApiTypeByIdResponses = {
    /**
     * OK
     */
    200: TypeDetailDto;
};

export type GetApiTypeByIdResponse = GetApiTypeByIdResponses[keyof GetApiTypeByIdResponses];

export type PutApiTypeByIdData = {
    body: UpdateTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Type/{id}';
};

export type PutApiTypeByIdResponses = {
    /**
     * OK
     */
    200: TypeDetailDto;
};

export type PutApiTypeByIdResponse = PutApiTypeByIdResponses[keyof PutApiTypeByIdResponses];

export type GetApiUserData = {
    body?: never;
    path?: never;
    query?: {
        SearchTerm?: string;
        MajorId?: string;
        TrustLevel?: string;
        EmailConfirmed?: boolean;
        IsDeleted?: boolean;
        SortBy?: string;
        SortDescending?: boolean;
        Page?: number;
        PageSize?: number;
        Skip?: number;
        Take?: number;
    };
    url: '/api/User';
};

export type GetApiUserResponses = {
    /**
     * OK
     */
    200: PagedResponseOfUserDto;
};

export type GetApiUserResponse = GetApiUserResponses[keyof GetApiUserResponses];

export type GetApiUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type GetApiUserByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUserByIdResponse = GetApiUserByIdResponses[keyof GetApiUserByIdResponses];

export type PutApiUserByIdData = {
    body: UpdateUserCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type PutApiUserByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUserByIdResponse = PutApiUserByIdResponses[keyof PutApiUserByIdResponses];

export type PostApiUserByIdBanData = {
    body: BanUserCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}/ban';
};

export type PostApiUserByIdBanResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiUserByIdUnbanData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}/unban';
};

export type PostApiUserByIdUnbanResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiUserByIdTrustScoreData = {
    body: ManageTrustScoreCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}/trust-score';
};

export type PutApiUserByIdTrustScoreResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUserByIdTrustScoreResponse = PutApiUserByIdTrustScoreResponses[keyof PutApiUserByIdTrustScoreResponses];

export type GetApiUserByIdTrustHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/User/{id}/trust-history';
};

export type GetApiUserByIdTrustHistoryResponses = {
    /**
     * OK
     */
    200: Array<UserTrustHistoryDto>;
};

export type GetApiUserByIdTrustHistoryResponse = GetApiUserByIdTrustHistoryResponses[keyof GetApiUserByIdTrustHistoryResponses];
